title: Cecilio García Quiros Website
baseurl: /
permalink: '/:title/'
plugins:
  - jekyll-menus
  - jekyll-seo-tag
collections:
  posts:
     permalink: '/posts/:name'
  posts2:
     permalink: '/posts2/:name'
     output: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
